# Generated by Django 2.2.13 on 2021-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210824_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred',
            field=models.IntegerField(default=0),
        ),
    ]
