# Generated by Django 2.2.13 on 2024-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_referred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='today',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
