# Generated by Django 2.2.13 on 2024-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pkey',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
