# Generated by Django 2.0.13 on 2020-12-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0003_auto_20160818_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='productinfo',
            field=models.CharField(max_length=1000, verbose_name='Product info'),
        ),
    ]
