# Generated by Django 2.2.3 on 2021-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0004_auto_20201219_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonseamlesstransaction',
            name='credit_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Credit Used'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Paid'),
        ),
    ]
