# Generated by Django 2.2.13 on 2021-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20210809_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='bene_id',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='ifsc',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='mobile_number',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='user_id',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='vpa',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
