# Generated by Django 2.2.13 on 2021-08-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A short label, generally used to define a task.', max_length=200, null=True)),
                ('imageURL', models.FileField(default='x', upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('taskid', models.IntegerField(default=0, unique=True)),
                ('perdaylimit', models.IntegerField(default=0)),
                ('todaydownload', models.IntegerField(default=0)),
                ('totallimit', models.IntegerField(default=0)),
                ('totaldownload', models.IntegerField(default=0)),
                ('kind', models.CharField(default='game', max_length=100)),
                ('day', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('rewards', models.FloatField(blank=True, default=0)),
                ('directs_played', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
    ]
