# Generated by Django 2.2.13 on 2021-08-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playedgame',
            old_name='count',
            new_name='odds',
        ),
        migrations.RemoveField(
            model_name='game',
            name='day',
        ),
        migrations.RemoveField(
            model_name='game',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='game',
            name='perdaylimit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='taskid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='todaydownload',
        ),
        migrations.RemoveField(
            model_name='game',
            name='totaldownload',
        ),
        migrations.RemoveField(
            model_name='game',
            name='totallimit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='day',
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='directs_played',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playedgame',
            name='bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playedgame',
            name='bet_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playedgame',
            name='bet_type',
            field=models.CharField(choices=[('odd-even', 'odd-even'), ('big-small', 'big-small'), ('exact-match', 'exact-match')], default='big-small', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playedgame',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.GameResult'),
            preserve_default=False,
        ),
    ]
