# Generated by Django 2.2.13 on 2021-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210812_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=0)),
                ('selected_plan', models.IntegerField(default=0)),
            ],
        ),
    ]
