# Generated by Django 2.2.13 on 2021-08-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='ser',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
