# Generated by Django 2.2.13 on 2021-08-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_playedgame_ser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_amount', models.IntegerField(default=3.3)),
                ('bet_type', models.CharField(choices=[('odd-even', 'odd-even'), ('exact-match', 'exact-match'), ('big-small', 'big-small')], max_length=100)),
                ('ser', models.IntegerField(default=18)),
                ('count', models.IntegerField(default=0)),
                ('empty_period', models.IntegerField(default=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
    ]
