# Generated by Django 2.2.13 on 2021-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20210821_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='odds',
            field=models.IntegerField(default=0),
        ),
    ]
