# Generated by Django 2.2.13 on 2021-08-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210821_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragon',
            old_name='count',
            new_name='counter',
        ),
    ]
