# Generated by Django 2.2.13 on 2021-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210822_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='bet_type',
            field=models.CharField(choices=[('odd-even', 'odd-even')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='starting_amount',
            field=models.FloatField(default=3.3),
        ),
    ]
