# Generated by Django 2.2.13 on 2021-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210822_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='increment',
            field=models.FloatField(default=1.03),
        ),
    ]
