# Generated by Django 2.2.13 on 2024-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_dragon_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='counter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='empty_period',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='ser',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='bet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='odds',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='ser',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
